import type { ClipCandidate } from '../types/clip';

export const mockClips: ClipCandidate[] = [
  {
    clip_id: 'c-001',
    file_id: 'f-A',
    file_name: 'DJI_0142.MP4',
    start_sec: 12.4,
    end_sec: 19.8,
    scores: { smoothness: 9.1, sharpness: 8.6, exposure: 8.2, contrast: 7.8, overall: 8.7 },
    reason: 'Stable 9.1/10, sharp, good exposure — long horizon glide.',
  },
  {
    clip_id: 'c-002',
    file_id: 'f-A',
    file_name: 'DJI_0142.MP4',
    start_sec: 47.0,
    end_sec: 53.6,
    scores: { smoothness: 8.4, sharpness: 7.9, exposure: 7.5, contrast: 7.2, overall: 8.0 },
    reason: 'Stable 8.4/10, sharp, slightly soft contrast on the descent.',
  },
  {
    clip_id: 'c-003',
    file_id: 'f-B',
    file_name: 'DJI_0148.MP4',
    start_sec: 3.2,
    end_sec: 9.6,
    scores: { smoothness: 7.6, sharpness: 8.4, exposure: 8.9, contrast: 8.1, overall: 8.0 },
    reason: 'Smooth 7.6/10, very sharp, excellent exposure on coastline.',
  },
  {
    clip_id: 'c-004',
    file_id: 'f-B',
    file_name: 'DJI_0148.MP4',
    start_sec: 22.1,
    end_sec: 28.0,
    scores: { smoothness: 7.2, sharpness: 6.5, exposure: 7.0, contrast: 6.8, overall: 7.0 },
    reason: 'Smooth 7.2/10, mild softness — usable b-roll.',
  },
  {
    clip_id: 'c-005',
    file_id: 'f-B',
    file_name: 'DJI_0148.MP4',
    start_sec: 41.5,
    end_sec: 46.0,
    scores: { smoothness: 6.4, sharpness: 5.9, exposure: 6.7, contrast: 6.2, overall: 6.3 },
    reason: 'Borderline 6.4/10 stability with minor jitter on the bank.',
  },
  {
    clip_id: 'c-006',
    file_id: 'f-C',
    file_name: 'DJI_0151.MP4',
    start_sec: 8.0,
    end_sec: 14.5,
    scores: { smoothness: 8.9, sharpness: 8.1, exposure: 5.8, contrast: 6.4, overall: 7.6 },
    reason: 'Stable 8.9/10 but underexposed at sunset — graded recovery likely.',
  },
  {
    clip_id: 'c-007',
    file_id: 'f-C',
    file_name: 'DJI_0151.MP4',
    start_sec: 31.4,
    end_sec: 35.9,
    scores: { smoothness: 4.6, sharpness: 7.5, exposure: 7.1, contrast: 7.2, overall: 5.4 },
    reason: 'Choppy 4.6/10 — visible micro-jitter on yaw.',
  },
  {
    clip_id: 'c-008',
    file_id: 'f-C',
    file_name: 'DJI_0151.MP4',
    start_sec: 58.0,
    end_sec: 64.2,
    scores: { smoothness: 8.0, sharpness: 8.8, exposure: 8.4, contrast: 8.0, overall: 8.3 },
    reason: 'Stable 8.0/10, very sharp ridgeline pass with strong exposure.',
  },
];
